addSbtPlugin("com.github.gseitz"     % "sbt-release"            % "1.0.8")
addSbtPlugin("org.xerial.sbt"        % "sbt-sonatype"           % "2.1")
addSbtPlugin("com.jsuereth"          % "sbt-pgp"                % "1.1.0")
addSbtPlugin("io.get-coursier"       % "sbt-coursier"           % "1.0.2")
addSbtPlugin("com.lucidchart"        % "sbt-scalafmt"           % "1.15")
addSbtPlugin("com.pigumer.sbt.cloud" % "sbt-aws-cloudformation" % "5.0.23")
addSbtPlugin("com.github.yoshiyoshifujii" % "sbt-aws-serverless" % "4.0.0-SNAPSHOT")
